---
title: "Cell Chat 2"
output: html_document
date: '2023-09-29'
---

```{r setup, include=FALSE}
############Install needed Packages

# Installation ------------------------------------------------------------
# install.packages("devtools")
install.packages('Seurat')                                          #install Seurat

devtools::install_github("satijalab/seurat-data", ref = 'develop')  #install Seurat-data

if (!requireNamespace("remotes", quietly = TRUE)) {                #install Seurat-disk
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")


devtools::install_github("sqjin/CellChat")                     #install cellchat

devtools::install_github("thomasp85/patchwork")                #install patchwork

setRepositories(ind=1:3) # needed to automatically install Bioconductor dependencies
install.packages("Signac")  #install signac

if (!require("BiocManager", quietly = TRUE))                  #install scater
  install.packages("BiocManager")

BiocManager::install("scater")

devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")    #install loomR
```


```{r }
#Load Required Libraries:
library(Seurat)
library(SeuratData)
library(SeuratDisk)
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
library(dplyr)
library(Signac)
library(loomR)
library(scater)
```


```{r}
x <- read.csv("C:\\Users\\Dell\\Downloads\\hvg_logNormcounts.csv",header=TRUE)
rownames(x) <- x[,1]
x[,1] <- NULL
print(dim(x))
print(x[1:5,1:5])


m <- read.csv("C:\\Users\\Dell\\Downloads\\metadata.csv",header=TRUE)
rownames(m) <- m[,1]
colnames(m)[1] <- "sample"
print(dim(m))
print(head(m))


saveRDS(
  CreateSeuratObject(counts=t(x),meta.data=m,project="seurat",min.cells=0,min.features=0),
  "seuratMMfinal.Rds"
)
```


```{r}
# Loading Data  -----------------------------------------------------------

Multiple_m<- readRDS("seuratMMfinal.Rds")
Multiple_m
```


```{r}
# Part I: Data input & processing and initialization of Cell Chat ----------
#1- Create a Cell Chat object

cellchat <- createCellChat(object = Multiple_m , group.by = "celltypist_cell_label_fine") 
cellchat <- setIdent(cellchat, ident.use = "celltypist_cell_label_fine") # set "cell_type" as default cell identity
levels(cellchat@idents) # show factor levels of the cell_type
groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group
groupSize
```


```{r}
#2- Set the ligand-receptor interaction database(Human)
CellChatDB <- CellChatDB.human # use Cell ChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)
```


```{r}
# Show the structure of the database
dplyr::glimpse(CellChatDB$interaction)
```


```{r}
# use a subset of CellChatDB for cell-cell communication analysis
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # Paracrine Autocrine Signaling interactions
```


```{r}
# use all CellChatDB for cell-cell communication analysis
# CellChatDB.use <- CellChatDB # simply use the default CellChatDB
# set the used database in the object
cellchat@DB <- CellChatDB.use
```

```{r}
#3-Preprocessing the expression data for cell-cell communication analysis
# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
#future::plan("multiprocess") # do parallel
cellchat <- identifyOverExpressedGenes(cellchat) #with 20 warnings
cellchat <- identifyOverExpressedInteractions(cellchat) # with warnings 
```


```{r}
# # Part II: Inference of cell-cell communication network -------- --------
#1-Compute the communication probability and infer cellular communication network
cellchat <- computeCommunProb(cellchat, type = "truncatedMean", trim = 0.1) # CellChat uses a statistically robust mean method called ‘tri-mean’ in default , truncated mean is the other option.
cellchat@options$parameter #Parameter_Values_Storage

# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat <- filterCommunication(cellchat, min.cells = 10)
```


```{r}
#2-Extract the inferred cellular communication network as a data frame
df.net <- subsetCommunication(cellchat)
View(df.net)

df.net1 <- subsetCommunication(cellchat, sources.use = c(3,4), targets.use = c(10,11))
View(df.net1)

#### CXCL13 expression was found to be strongly induced by the interactions between MM cell lines and microenvironment cells, including BM stromal cells and macrophages.
####Galectins have a role in hematopoietic differentiation, in particular creating specific galectin–glycan interactions between hematopoietic and stromal cells, sustaining the formation of a microenvironmental niche
df.net2<- subsetCommunication(cellchat, signaling = c("MK", "CCL"))

View(df.net2)
```


```{r}
#3-Infer the cell-cell communication at a signaling pathway level
cellchat <- computeCommunProbPathway(cellchat)
View(cellchat@netP)
cellchat@netP$pathways   
cellchat@netP[["pathways"]]
```


```{r}
#4-Calculate the aggregated cell-cell communication network
cellchat <- aggregateNet(cellchat) #Counting Number of links 
cellchat

#We can also VISUALIZE the aggregated cell-cell communication network using CIRCLE plot.

groupSize
```


```{r}
#showing the number of interactions:
par(mfrow = c(1,2), xpd=TRUE) # Display 1 row 2 column / xpd = true all plotting is clipped to the figure region,
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, 
                 weight.scale = T, label.edge= F, 
                 title.name = "Number of interactions")
```
```{r}
#Showing the total interaction strength (weights) between any two cell groups:
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, 
                 weight.scale = T, label.edge= F, 
                 title.name = "Interaction weights/strength")
```


```{r}
#Due to the complicated cell-cell communication network, we can examine the signaling sent from each cell group. 
#By controlling the parameter edge.weight.max,edge weights between different networks can be compared.
mat <- cellchat@net$weight
par(mfrow = c(2,3), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}
```


```{r}
# # Part III: Visualization of cell-cell communication network  -----------

#Visualize each signaling pathway using Circle plot, Chord diagram or heat map


```
```{r}
cellchat@netP$pathways #All the signaling pathways showing significant communications  
pathways.show <- c("CXCL")
```


```{r}
#1- Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```


```{r}
pdf(file ="cellchat_chordplotCXCL.pdf", width = 20, height =16)

#2-Chord diagram
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
dev.off()
```

```{r}
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
```{r}
#Compute the contribution of each ligand-receptor pair to the overall signaling 
netAnalysis_contribution(cellchat, signaling = pathways.show) 

#visualize the cell-cell communication mediated by a single ligand-receptor pair. 
#The function EnrichedLR extracts all the significant interactions (L-R pairs) and related signaling genes for a given signaling pathway.
pairLR.EGVF <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.EGVF[1,] # show one ligand-receptor pair
```



```{r}

cellchat@netP$pathways #All the signaling pathways showing significant communications  
pathways.show <- c("SPP1")
```


```{r}
#1- Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```


```{r}
pdf(file ="cellchat_chordplotSPP1.pdf", width = 20, height =16)

#2-Chord diagram
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
dev.off()
```


```{r}
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
```{r}
#Compute the contribution of each ligand-receptor pair to the overall signaling 
netAnalysis_contribution(cellchat, signaling = pathways.show) 

#visualize the cell-cell communication mediated by a single ligand-receptor pair. 
#The function EnrichedLR extracts all the significant interactions (L-R pairs) and related signaling genes for a given signaling pathway.
pairLR.EGVF <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.EGVF[1,] # show one ligand-receptor pair
```


```{r}
cellchat@netP$pathways #All the signaling pathways showing significant communications  
pathways.show <- c("MK")

```


```{r}
#1- Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")


```


```{r fig4, out.width = '40%'}

pdf(file ="cellchat_chordplot1.pdf", width = 20, height =16)

#2-Chord diagram
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
dev.off()

```


```{r}
#3-Heat map
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
```{r}
#Compute the contribution of each ligand-receptor pair to the overall signaling 
netAnalysis_contribution(cellchat, signaling = pathways.show) 

#visualize the cell-cell communication mediated by a single ligand-receptor pair. 
#The function EnrichedLR extracts all the significant interactions (L-R pairs) and related signaling genes for a given signaling pathway.
pairLR.EGVF <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.EGVF[1,] # show one ligand-receptor pair

```


```{r}
# Circle plot
netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "circle")
```

```{r}

pdf(file ="Ligand_receptor_MK.pdf", width = 20, height =16)
# Chord diagram
netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "chord")
dev.off()
```
```{r}
cellchat@netP$pathways #All the signaling pathways showing significant communications  
pathways.show <- c("TNF")

```


```{r}
#1- Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")

```


```{r}
#3-Heat map
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
```{r}

```


```{r}

#Compute the contribution of each ligand-receptor pair to the overall signaling 
netAnalysis_contribution(cellchat, signaling = pathways.show) 

#visualize the cell-cell communication mediated by a single ligand-receptor pair. 
#The function EnrichedLR extracts all the significant interactions (L-R pairs) and related signaling genes for a given signaling pathway.
pairLR.EGVF <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.EGVF[1,] # show one ligand-receptor pair

```


```{r}
cellchat@netP$pathways #All the signaling pathways showing significant communications  
pathways.show <- c("CCL")

```


```{r}
#1- Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```

```{r}
#3-Heat map
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
```{r}
pdf(file ="Ligand_receptor_CCL.pdf", width = 20, height =16)
# Chord diagram
netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "chord")
dev.off()
```


```{r}
#Compute the contribution of each ligand-receptor pair to the overall signaling 
netAnalysis_contribution(cellchat, signaling = pathways.show) 

#visualize the cell-cell communication mediated by a single ligand-receptor pair. 
#The function EnrichedLR extracts all the significant interactions (L-R pairs) and related signaling genes for a given signaling pathway.
pairLR.EGVF <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.EGVF[1,] # show one ligand-receptor pair

```


```{r}
```


```{r}
# Access all the signaling pathways showing significant communications
pathways.show.all <- cellchat@netP$pathways
# check the order of cell identity to set suitable vertex.receiver
levels(cellchat@idents)
vertex.receiver = seq(1,2)
for (i in 1:length(pathways.show.all)) {
  # Visualize communication network associated with both signaling pathway and individual L-R pairs
  netVisual(cellchat, signaling = pathways.show.all[i], vertex.receiver = vertex.receiver, layout = "hierarchy")
  # Compute and visualize the contribution of each ligand-receptor pair to the overall signaling pathway
  gg <- netAnalysis_contribution(cellchat, signaling = pathways.show.all[i])
  ggsave(filename=paste0(pathways.show.all[i], "_L-R_contribution.pdf"), plot=gg, width = 3, height = 2, units = 'in', dpi = 300)
}
```


```{r}
##Visualize cell-cell communication mediated by MULTIPLE LIGAND-RECEPTORS or signaling pathways
#a-Bubble plot 
# show all the significant interactions (L-R pairs) from some cell groups (defined by 'sources.use' Macro) to other cell groups (defined by 'targets.use' all)
#1) HSC/MPP
netVisual_bubble(cellchat, sources.use =8, targets.use = c(3:17), remove.isolate = FALSE)
#> Comparing communications on a single object
```


```{r}
#########1)MK

# show all the significant interactions (L-R pairs) associated with certain signaling pathway (MK)
netVisual_bubble(cellchat, sources.use = 11, targets.use = c(3:17), signaling = c("MK"), remove.isolate = FALSE)

```
```{r}

# show all the significant interactions (L-R pairs) based on user's input (defined by `pairLR.use`)
pairLR.use <- extractEnrichedLR(cellchat, signaling = c("CCL","CXCL", "SPP1","VISFATIN"))
netVisual_bubble(cellchat, sources.use = c(8,11), targets.use = c(3:17), pairLR.use = pairLR.use, remove.isolate = TRUE)
```

```{r}
pairLR.use <- extractEnrichedLR(cellchat, signaling = c("CCL","CXCL", "SPP1","VISFATIN","TNF"))
netVisual_bubble(cellchat, sources.use = c(4), targets.use = c(3:17), pairLR.use = pairLR.use, remove.isolate = TRUE)
```

```{r}
pairLR.use <- extractEnrichedLR(cellchat, signaling = c("SPP1","TNF","CCL","MK"))
netVisual_bubble(cellchat, sources.use = c(11), targets.use = c(3:17), pairLR.use = pairLR.use, remove.isolate = TRUE)
```

```{r}

#c-Plot the signaling gene expression distribution using violin/dot plot

plotGeneExpression(cellchat, signaling = "VISFATIN")
plotGeneExpression(cellchat, signaling = "CCL")
plotGeneExpression(cellchat, signaling = "CXCL")
plotGeneExpression(cellchat, signaling = "SPP1")


```


```{r}
#show the expression of all signaling genes related to one signaling pathway
plotGeneExpression(cellchat, signaling = "MK", enriched.only = FALSE)
```
```{r}
#show the expression of all signaling genes related to one signaling pathway
#"GALECTIN" "MK"       "BAFF"     "CXCL"     "VISFATIN" "CCL"      "TNF"      "CALCR"   
plotGeneExpression(cellchat, signaling = "SPP1", enriched.only = FALSE)
```


```{r}
#"GALECTIN" "MK"       "BAFF"     "CXCL"     "VISFATIN" "CCL"      "TNF"      "CALCR"   
plotGeneExpression(cellchat, signaling = "CCL", enriched.only = FALSE)
```


```{r}
plotGeneExpression(cellchat, signaling = "TNF", enriched.only = FALSE)
```



```{r}
#"GALECTIN" "MK"       "BAFF"     "CXCL"     "VISFATIN" "CCL"      "TNF"      "CALCR"   
plotGeneExpression(cellchat, signaling = "VISFATIN", enriched.only = FALSE)
```


```{r}
# # Part V: Save the CellChat object- -------------------------------------

saveRDS(cellchat, file = "cellchat_Multiple_Myeloma_final.rds")
```


```


```{r }
```


```{r}
```


```{r}
```


```{r}
```


```{r }

```


```{r }

```

```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

